 name: 'Stategraph'
 on:
   workflow_dispatch:
     inputs:
       # The work-token and api-base-url are automatically passed in by the Stategraph backend
       work-token:
         description: 'Work Token'
         required: true
       api-base-url:
         description: 'API Base URL'
       environment:
         description: 'Environment in which to run the action'
         type: environment
       runs_on:
         description: 'runs-on configuration'
         type: string
         default: '"ubuntu-latest"'
 jobs:
   stategraph:
     permissions: # Required to pass credentials to the Stategraph action
       id-token: write
       contents: read
     runs-on: ${{ fromJSON(github.event.inputs.runs_on) }}
     timeout-minutes: 1440
     name: Stategraph
     environment: '${{ github.event.inputs.environment }}'
     steps:
       - uses: actions/checkout@v4
       - name: Run Stategraph
         id: stategraph
         uses: terrateamio/action@v1
         with:
           work-token: '${{ github.event.inputs.work-token }}'
           api-base-url: '${{ github.event.inputs.api-base-url }}'
         env:
           SECRETS_CONTEXT: ${{ toJson(secrets) }}
           VARIABLES_CONTEXT: ${{ toJson(vars) }}
